import { theme, type ThemeConfig } from 'antd';

// Design tokens in one place. Deep teal primary, cool slate-green neutrals, soft borders with a hairline shadow,
// 12px radius on controls and 16px on surfaces. Controls are 40px high so they are easy to hit on a tablet.
export const COLORS = {
  primary: '#0A6C74',
  primaryHover: '#07535A',
  primarySoft: '#E3F2F3',
  ink: '#10242E',
  text: '#1D3440',
  muted: '#4F6570',
  faint: '#5B717C',
  line: '#E3E9EC',
  lineSoft: '#EEF2F4',
  page: '#F3F6F7',
  surface: '#FFFFFF',
  surfaceAlt: '#F7F9FA',
  sidebar: '#FFFFFF',
  // Status tones: one mapping for the whole app (see StatusTag).
  good: { fg: '#12704A', bg: '#E3F4EB', dot: '#1E8C5A' },
  warn: { fg: '#8A5A06', bg: '#FCF1D8', dot: '#E0A93B' },
  bad: { fg: '#B2330E', bg: '#FDE8E1', dot: '#D2552B' },
  info: { fg: '#1F4FB4', bg: '#E6EEFC', dot: '#2F6FDB' },
  neutral: { fg: '#3F5560', bg: '#EEF2F4', dot: '#9AAAB2' },
} as const;

export const appTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: COLORS.primary,
    colorInfo: COLORS.info.dot,
    colorSuccess: COLORS.good.dot,
    colorWarning: COLORS.warn.dot,
    colorError: '#C2410C',
    colorLink: COLORS.primary,
    colorLinkHover: COLORS.primaryHover,
    colorBgLayout: COLORS.page,
    colorBgContainer: COLORS.surface,
    colorBorder: '#D5DEE2',
    colorBorderSecondary: COLORS.line,
    colorText: COLORS.text,
    colorTextHeading: COLORS.ink,
    colorTextSecondary: COLORS.muted,
    colorTextTertiary: COLORS.faint,
    colorTextPlaceholder: '#7D8F98',
    colorFillAlter: COLORS.surfaceAlt,
    borderRadius: 10,
    borderRadiusLG: 16,
    borderRadiusSM: 8,
    fontSize: 14,
    lineHeight: 1.5,
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    boxShadow: '0 1px 2px rgba(16, 36, 46, 0.04)',
    boxShadowSecondary: '0 12px 32px rgba(16, 36, 46, 0.14)',
    fontFamily: 'var(--font-sans), system-ui, -apple-system, "Segoe UI", sans-serif',
  },
  components: {
    Layout: { siderBg: COLORS.sidebar, headerBg: COLORS.surface, headerHeight: 68, headerPadding: '0 28px', bodyBg: COLORS.page },
    Menu: {
      itemBg: COLORS.sidebar,
      itemColor: COLORS.muted,
      itemHoverColor: COLORS.ink,
      itemHoverBg: COLORS.page,
      itemSelectedBg: COLORS.primarySoft,
      itemSelectedColor: COLORS.primaryHover,
      groupTitleColor: COLORS.faint,
      groupTitleFontSize: 11,
      itemBorderRadius: 10,
      itemHeight: 42,
      iconSize: 17,
      itemMarginInline: 0,
      itemMarginBlock: 2,
      activeBarBorderWidth: 0,
    },
    Card: { headerFontSize: 16, headerHeight: 56, colorBorderSecondary: COLORS.line, paddingLG: 20 },
    Table: {
      headerBg: '#FAFBFC',
      headerColor: COLORS.faint,
      headerSplitColor: 'transparent',
      rowHoverBg: '#F5F9F9',
      borderColor: COLORS.lineSoft,
      cellPaddingBlock: 14,
      cellPaddingInline: 16,
      cellPaddingBlockSM: 12,
      cellPaddingInlineSM: 10,
    },
    Tabs: { horizontalMargin: '0 0 20px', titleFontSize: 14, itemColor: COLORS.faint, itemSelectedColor: COLORS.primaryHover, inkBarColor: COLORS.primary },
    Button: { fontWeight: 600, primaryShadow: 'none', defaultShadow: 'none', dangerShadow: 'none', paddingInline: 18, borderRadius: 10 },
    Form: { labelColor: COLORS.ink, labelFontSize: 13.5, verticalLabelPadding: '0 0 6px', itemMarginBottom: 22, labelRequiredMarkColor: COLORS.bad.fg },
    Input: { activeShadow: '0 0 0 3px rgba(10, 108, 116, 0.16)', paddingInline: 12 },
    InputNumber: { activeShadow: '0 0 0 3px rgba(10, 108, 116, 0.16)' },
    Select: { optionSelectedBg: COLORS.primarySoft, optionSelectedFontWeight: 600 },
    DatePicker: { activeShadow: '0 0 0 3px rgba(10, 108, 116, 0.16)' },
    Tag: { defaultBg: COLORS.lineSoft, defaultColor: COLORS.text },
    Modal: { titleFontSize: 18, borderRadiusLG: 16 },
    Drawer: { paddingLG: 24 },
    Descriptions: { labelBg: 'transparent', labelColor: COLORS.faint, titleMarginBottom: 12 },
    Segmented: { trackBg: '#E7EDEF', itemSelectedColor: COLORS.ink, borderRadius: 12, borderRadiusSM: 9 },
    Alert: { withDescriptionPadding: '14px 18px', borderRadiusLG: 14 },
    Skeleton: { gradientFromColor: '#EDF1F3', gradientToColor: '#F6F8F9', borderRadiusSM: 8 },
    Badge: { colorError: '#C2410C' },
    Pagination: { itemActiveBg: COLORS.primarySoft },
  },
};
