import { theme, type ThemeConfig } from 'antd';

// Design tokens in one place. Calm teal primary, cool slate neutrals, soft borders instead of shadows,
// 10px radius on surfaces. Controls are 38px high so they are easy to hit on a tablet.
export const COLORS = {
  primary: '#0E7490',
  primarySoft: '#E6F4F8',
  ink: '#0F172A',
  text: '#1E293B',
  muted: '#526173',
  faint: '#667385',
  line: '#E2E8F0',
  lineSoft: '#EEF2F6',
  page: '#F4F6F9',
  surface: '#FFFFFF',
  sidebar: '#0F1B2D',
  // Status tones: one mapping for the whole app (see StatusTag).
  good: { fg: '#047857', bg: '#E7F6EF', dot: '#10B981' },
  warn: { fg: '#B45309', bg: '#FEF3DC', dot: '#F59E0B' },
  bad: { fg: '#B91C1C', bg: '#FDECEC', dot: '#EF4444' },
  info: { fg: '#1D4ED8', bg: '#E8F0FE', dot: '#3B82F6' },
  neutral: { fg: '#475569', bg: '#EEF2F6', dot: '#94A3B8' },
} as const;

export const appTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: COLORS.primary,
    colorInfo: '#2563EB',
    colorSuccess: '#10B981',
    colorWarning: '#F59E0B',
    colorError: '#DC2626',
    colorLink: COLORS.primary,
    colorBgLayout: COLORS.page,
    colorBgContainer: COLORS.surface,
    colorBorder: '#D5DDE6',
    colorBorderSecondary: COLORS.line,
    colorText: COLORS.text,
    colorTextHeading: COLORS.ink,
    colorTextSecondary: COLORS.muted,
    colorTextTertiary: COLORS.muted,
    colorTextPlaceholder: COLORS.faint,
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 6,
    fontSize: 14,
    lineHeight: 1.5,
    controlHeight: 38,
    controlHeightLG: 46,
    controlHeightSM: 30,
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04)',
    boxShadowSecondary: '0 8px 24px rgba(15, 23, 42, 0.12)',
    fontFamily: 'var(--font-inter), system-ui, -apple-system, "Segoe UI", sans-serif',
  },
  components: {
    Layout: { siderBg: COLORS.sidebar, headerBg: COLORS.surface, headerHeight: 60, headerPadding: '0 24px', bodyBg: COLORS.page },
    Menu: {
      darkItemBg: COLORS.sidebar,
      darkSubMenuItemBg: COLORS.sidebar,
      darkItemColor: '#A9B7C9',
      darkItemHoverColor: '#FFFFFF',
      darkItemHoverBg: 'rgba(255,255,255,0.06)',
      darkItemSelectedBg: 'rgba(14, 116, 144, 0.55)',
      darkItemSelectedColor: '#FFFFFF',
      darkGroupTitleColor: '#9AABC0',
      itemBorderRadius: 8,
      itemHeight: 40,
      iconSize: 16,
      itemMarginInline: 0,
    },
    Card: { headerFontSize: 15, headerHeight: 52, colorBorderSecondary: COLORS.line },
    Table: {
      headerBg: '#F8FAFC',
      headerColor: COLORS.muted,
      headerSplitColor: 'transparent',
      rowHoverBg: '#F5F9FB',
      borderColor: COLORS.lineSoft,
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
    },
    Tabs: { horizontalMargin: '0 0 16px', titleFontSize: 14, itemColor: COLORS.muted },
    Button: { fontWeight: 500, primaryShadow: 'none', defaultShadow: 'none', paddingInline: 16 },
    Input: { activeShadow: '0 0 0 3px rgba(14, 116, 144, 0.14)' },
    Select: { optionSelectedBg: COLORS.primarySoft },
    Tag: { defaultBg: COLORS.lineSoft, defaultColor: COLORS.text },
    Modal: { titleFontSize: 17 },
    Descriptions: { labelBg: 'transparent' },
    Segmented: { trackBg: '#E9EEF3' },
    Alert: { withDescriptionPadding: '12px 16px' },
  },
};
