import { rm } from 'node:fs/promises';
import path from 'node:path';
import { prisma } from '../apps/api/src/lib/prisma';
const assets = await prisma.asset.findMany({ where: { OR: [{ name: { startsWith: 'E2E-' } }, { name: { startsWith: 'UX-' } }, { name: { startsWith: 'E2E' } }] }, select: { id: true } });
const ids = assets.map((a) => a.id);
const complaints = await prisma.complaint.findMany({ where: { OR: [{ assetId: { in: ids } }, { description: { startsWith: 'E2E' } }] }, select: { id: true } });
const logs = await prisma.serviceLog.findMany({ where: { assetId: { in: ids } }, select: { id: true } });
const exps = await prisma.serviceExpense.findMany({ where: { assetId: { in: ids } }, select: { id: true } });
const pos = await prisma.purchaseOrder.findMany({ where: { assetId: { in: ids } }, select: { id: true } });
const owners = [...ids, ...complaints.map((c) => c.id), ...logs.map((l) => l.id), ...exps.map((e) => e.id), ...pos.map((p) => p.id)];
const files = await prisma.attachment.findMany({ where: { ownerId: { in: owners } } });
const root = path.resolve(process.env.STORAGE_PATH ?? 'apps/api/uploads');
for (const f of files) await rm(path.join(root, f.filePath), { force: true });
await prisma.attachment.deleteMany({ where: { ownerId: { in: owners } } });
await prisma.serviceExpense.deleteMany({ where: { assetId: { in: ids } } });
await prisma.complaint.deleteMany({ where: { id: { in: complaints.map((c) => c.id) } } });
await prisma.serviceLog.deleteMany({ where: { assetId: { in: ids } } });
await prisma.purchaseOrder.deleteMany({ where: { assetId: { in: ids } } });
await prisma.serviceContract.deleteMany({ where: { assetId: { in: ids } } });
await prisma.calibrationRecord.deleteMany({ where: { assetId: { in: ids } } });
await prisma.$transaction([prisma.$queryRaw`select set_config('bme.allow_pms_cleanup', 'on', true)`, prisma.pmsRecord.deleteMany({ where: { assetId: { in: ids } } })]);
await prisma.approvalRequest.deleteMany({ where: { targetId: { in: owners } } });
await prisma.notification.deleteMany({ where: { assetId: { in: ids } } });
await prisma.asset.deleteMany({ where: { id: { in: ids } } });
const types = await prisma.equipmentType.findMany({ where: { code: 'E2ET' }, select: { id: true } });
await prisma.pmsTemplate.deleteMany({ where: { equipmentTypeId: { in: types.map((t) => t.id) } } });
await prisma.asset.deleteMany({ where: { equipmentTypeId: { in: types.map((t) => t.id) } } }).catch(() => {});
await prisma.equipmentType.deleteMany({ where: { id: { in: types.map((t) => t.id) } } }).catch((e) => console.log('type left:', String(e).slice(0, 80)));
await prisma.location.deleteMany({ where: { department: { code: 'E2D' } } });
await prisma.department.deleteMany({ where: { code: 'E2D' } }).catch(() => {});
const users = await prisma.user.deleteMany({ where: { email: { startsWith: 'e2e.' } } }).catch((e) => { console.log('users left (referenced):', String(e).slice(0, 60)); return { count: 0 }; });
console.log('e2e users removed:', users.count);
console.log({ assets: ids.length, complaints: complaints.length, files: files.length });
await prisma.$disconnect();
