import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import type { ChartSpec, ReportData, ValueFmt } from '@bme/shared';
import { config } from '../../lib/config';
import { parseDate } from '../../lib/dates';

// Excel and PDF are made from the same ReportData the screen shows, so the three never disagree.

const NUM_FMT: Partial<Record<ValueFmt, string>> = {
  date: 'dd mmm yyyy',
  money: '"₹" #,##0.00',
  hours: '#,##0.0',
  pct: '0.0%',
  int: '#,##0',
  years: '0.0',
};

const stamp = (iso: string) =>
  new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false, timeZone: config.timezone })
    .format(new Date(iso))
    .replace(/(\d{4}) /, '$1, ');

const period = (d: ReportData) => (d.from && d.to ? `${prettyDay(d.from)} to ${prettyDay(d.to)}` : 'As at today');
const prettyDay = (iso: string) => new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' }).format(parseDate(iso));

// ---------- Excel ----------

export function toWorkbook(data: ReportData): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = data.generatedBy;
  wb.created = new Date(data.generatedAt);

  const sheet = (name: string, columns: { header: string; key: string; fmt?: ValueFmt; width?: number }[], rows: Record<string, unknown>[], totals?: string[]) => {
    const ws = wb.addWorksheet(name, { views: [{ state: 'frozen', ySplit: 1 }] });
    ws.columns = columns.map((c) => ({ header: c.header, key: c.key, width: c.width ?? Math.max(12, c.header.length + 2) }));
    // Dates travel as YYYY-MM-DD; Excel gets real dates so they sort and filter.
    ws.addRows(rows.map((r) => Object.fromEntries(columns.map((c) => [c.key, c.fmt === 'date' && typeof r[c.key] === 'string' ? parseDate(r[c.key] as string) : r[c.key]]))));
    columns.forEach((c, i) => {
      const f = c.fmt && NUM_FMT[c.fmt];
      if (f) ws.getColumn(i + 1).numFmt = f;
    });
    const header = ws.getRow(1);
    header.font = { bold: true };
    header.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE5E7EB' } };
    if (rows.length) ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: columns.length } };
    if (totals && rows.length) {
      const total: Record<string, unknown> = { [columns[0].key]: 'Total' };
      for (const key of totals) total[key] = rows.reduce((sum, r) => sum + (Number(r[key]) || 0), 0);
      ws.addRow(total).font = { bold: true };
    }
  };

  for (const s of data.sheets) sheet(s.name, s.columns, s.rows, s.totals);
  if (data.kpis.length) {
    sheet('Highlights', [{ header: 'Measure', key: 'k', width: 34 }, { header: 'Value', key: 'v', width: 22 }, { header: 'Note', key: 'n', width: 44 }], data.kpis.map((k) => ({ k: k.label, v: k.fmt === 'pct' && typeof k.value === 'number' ? `${(k.value * 100).toFixed(1)}%` : k.value, n: k.hint ?? '' })));
  }
  sheet('About', [{ header: 'Item', key: 'k', width: 20 }, { header: 'Value', key: 'v', width: 60 }], [
    { k: 'Hospital', v: data.hospital },
    { k: 'Report', v: data.title },
    { k: 'Period', v: period(data) },
    { k: 'Generated', v: stamp(data.generatedAt) },
    { k: 'Generated by', v: data.generatedBy },
    ...(data.note ? [{ k: 'Note', v: data.note }] : []),
  ]);
  return wb;
}

// ---------- PDF ----------

const INK = '#0F172A';
const MUTED = '#64748B';
const LINE = '#E2E8F0';
const SERIES = ['#0891B2', '#eb6834', '#4a3aa7'];
const PAGE = { w: 841.89, h: 595.28, m: 32 }; // A4 landscape
const USABLE = PAGE.w - PAGE.m * 2;

// The built-in PDF font has no rupee sign, so money reads "Rs. 12,500" here (Excel and the screen use ₹).
const num = (n: number, digits = 0) => new Intl.NumberFormat('en-IN', { maximumFractionDigits: digits, minimumFractionDigits: digits }).format(n);
export function formatValue(v: unknown, fmt: ValueFmt | undefined, unit = false): string {
  if (v == null || v === '') return '-';
  if (typeof v === 'string') return fmt === 'date' && /^\d{4}-\d{2}-\d{2}$/.test(v) ? prettyDay(v) : v; // the totals row says "Total" even in a date column
  if (typeof v !== 'number') return String(v);
  switch (fmt) {
    case 'money':
      return `Rs. ${num(v, 0)}`;
    case 'pct':
      return `${num(v * 100, 1)}%`;
    case 'hours':
      return unit ? `${num(v, 1)} h` : num(v, 1);
    case 'years':
      return unit ? `${num(v, 1)} y` : num(v, 1);
    default:
      return num(v, Number.isInteger(v) ? 0 : 1);
  }
}

export function toPdf(data: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: PAGE.m, bufferPages: true, info: { Title: data.title, Author: data.generatedBy } });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Our own cursor: PDFKit moves its own whenever text is drawn, which would shift everything drawn after.
    let y = PAGE.m;
    const bottom = () => PAGE.h - PAGE.m - 14;
    const need = (h: number) => {
      if (y + h > bottom()) {
        doc.addPage();
        y = PAGE.m;
      }
    };
    const text = (s: string, x: number, y: number, o: { w?: number; h?: number; size?: number; bold?: boolean; color?: string; align?: 'left' | 'right' | 'center' } = {}) => {
      // One line, cut with an ellipsis when it does not fit (a fixed height is what makes PDFKit truncate, not wrap).
      doc.font(o.bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(o.size ?? 8).fillColor(o.color ?? INK).text(s, x, y, { width: o.w, height: o.h ?? (o.size ?? 8) + 2, align: o.align, ellipsis: true });
    };

    // Title block
    text(data.hospital, PAGE.m, PAGE.m, { size: 9, color: MUTED });
    text(data.title, PAGE.m, PAGE.m + 13, { size: 20, bold: true });
    text(`${period(data)}   |   Generated ${stamp(data.generatedAt)} by ${data.generatedBy}`, PAGE.m, PAGE.m + 40, { size: 8.5, color: MUTED });
    y = PAGE.m + 60;

    // Headline figures
    if (data.kpis.length) {
      const perRow = data.kpis.length <= 5 ? data.kpis.length : data.kpis.length % 3 === 0 ? 3 : 4;
      const gap = 8;
      const w = (USABLE - gap * (perRow - 1)) / perRow;
      data.kpis.forEach((k, i) => {
        if (i > 0 && i % perRow === 0) y += 54;
        need(54);
        const x = PAGE.m + (i % perRow) * (w + gap);
        doc.roundedRect(x, y, w, 46, 4).lineWidth(0.6).strokeColor(LINE).stroke();
        text(k.label, x + 8, y + 6, { w: w - 16, size: 7.5, color: MUTED });
        text(formatValue(k.value, k.fmt, true), x + 8, y + 17, { w: w - 16, size: 15, bold: true });
        if (k.hint) text(k.hint, x + 8, y + 36, { w: w - 16, size: 6.5, color: k.tone === 'bad' ? '#B91C1C' : k.tone === 'warn' ? '#B45309' : MUTED });
      });
      y += 66;
    }

    // Charts as plain bars: label, bar, value. Enough to read the shape; the tables carry the detail.
    const bars = (c: ChartSpec) => {
      const rows = c.data.slice(0, c.kind === 'bar' ? 10 : 24);
      need(30 + rows.length * 12);
      text(c.title, PAGE.m, y, { size: 10, bold: true });
      if (c.subtitle) text(c.subtitle, PAGE.m + 260, y + 1.5, { size: 7.5, color: MUTED });
      y += 18;
      if (c.series.length > 1) {
        c.series.forEach((s, i) => {
          doc.rect(PAGE.m + 300 + i * 90, y - 14, 7, 7).fill(SERIES[i % SERIES.length]);
          text(s.label, PAGE.m + 311 + i * 90, y - 14, { size: 7.5, color: MUTED });
        });
      }
      const totalOf = (r: ChartSpec['data'][number]) => c.series.reduce((t, s) => t + (Number(r[s.key]) || 0), 0);
      const max = Math.max(1, ...rows.map(totalOf));
      const barW = 330;
      for (const r of rows) {
        text(r.label, PAGE.m, y, { w: 170, size: 7.5 });
        let x = PAGE.m + 180;
        c.series.forEach((s, i) => {
          const v = Number(r[s.key]) || 0;
          const w = (v / max) * barW;
          if (w > 0) doc.rect(x, y, Math.max(w - (c.series.length > 1 ? 1 : 0), 0.6), 7).fill(SERIES[i % SERIES.length]);
          x += w;
        });
        text(formatValue(totalOf(r), c.fmt, true), PAGE.m + 180 + barW + 8, y, { w: 90, size: 7.5, color: MUTED });
        y += 12;
      }
      y += 12;
    };
    data.charts.forEach(bars);

    // Tables
    for (const s of data.sheets) {
      const cols = s.columns.filter((c) => c.pdf !== false);
      const size = cols.length > 11 ? 6 : cols.length > 8 ? 6.5 : 7.5;
      // Column widths from the content: short values (dates, numbers) keep their full width, long text gives way.
      const measure = (t: string, bold = false) => doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(size).widthOfString(t);
      const natural = cols.map((c) => {
        const head = Math.max(...c.header.split(' ').map((w) => measure(w, true)));
        const cells = s.rows.slice(0, 60).map((r) => measure(formatValue(r[c.key], c.fmt)));
        return Math.min(180, Math.max(head, ...cells, 18)) + 8;
      });
      const widths = (() => {
        const need = natural.reduce((t, w) => t + w, 0);
        if (need <= USABLE) return natural.map((w) => (w / need) * USABLE); // spread the spare room
        const w = [...natural];
        for (let pass = 0; pass < 6 && w.reduce((t, x) => t + x, 0) > USABLE; pass++) {
          const over = w.reduce((t, x) => t + x, 0) - USABLE;
          const long = w.map((x, i) => (x > 90 ? i : -1)).filter((i) => i >= 0);
          if (!long.length) break;
          const cut = Math.min(...long.map((i) => w[i] - 70), over / long.length);
          if (cut <= 0) break;
          long.forEach((i) => (w[i] -= cut));
        }
        const total = w.reduce((t, x) => t + x, 0);
        return total > USABLE ? w.map((x) => (x / total) * USABLE) : w;
      })();
      const rowH = size + 8;
      const headH = size * 2 + 8; // headers may use two lines
      const align = (c: (typeof cols)[number]) => (c.fmt && c.fmt !== 'date' && c.fmt !== 'text' ? 'right' : 'left');

      const head = () => {
        doc.rect(PAGE.m, y, USABLE, headH).fill('#F1F5F9');
        let x = PAGE.m;
        cols.forEach((c, i) => {
          text(c.header, x + 3, y + 4, { w: widths[i] - 6, h: size * 2 + 2, size, bold: true, color: MUTED, align: align(c) });
          x += widths[i];
        });
        y += headH;
      };

      need(60);
      text(s.name, PAGE.m, y, { size: 11, bold: true });
      y += 18;
      if (!s.rows.length) {
        text('No rows.', PAGE.m, y, { size: 8, color: MUTED });
        y += 22;
        continue;
      }
      head();
      const line = (row: Record<string, unknown>, bold = false) => {
        if (y + rowH > bottom()) {
          doc.addPage();
          y = PAGE.m;
          head();
        }
        let x = PAGE.m;
        cols.forEach((c, i) => {
          text(formatValue(row[c.key], c.fmt), x + 3, y + 4, { w: widths[i] - 6, size, bold, align: align(c) });
          x += widths[i];
        });
        doc.moveTo(PAGE.m, y + rowH).lineTo(PAGE.m + USABLE, y + rowH).lineWidth(0.3).strokeColor(LINE).stroke();
        y += rowH;
      };
      s.rows.forEach((r) => line(r));
      if (s.totals?.length) line({ [cols[0].key]: 'Total', ...Object.fromEntries(s.totals.map((k) => [k, s.rows.reduce((t, r) => t + (Number(r[k]) || 0), 0)])) }, true);
      y += 16;
    }
    if (data.note) {
      need(20);
      text(data.note, PAGE.m, y, { size: 7.5, color: MUTED });
    }

    // Page numbers, written last so the total is known.
    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(range.start + i);
      doc.page.margins.bottom = 0; // otherwise writing in the margin starts a new page
      text(`${data.title}  |  ${data.hospital}`, PAGE.m, PAGE.h - 24, { size: 7, color: MUTED });
      text(`Page ${i + 1} of ${range.count}`, PAGE.m, PAGE.h - 24, { w: USABLE, size: 7, color: MUTED, align: 'right' });
    }
    doc.end();
  });
}
