import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

// Where uploaded files live: local disk (on-prem) or Supabase Storage (demo). Chosen by STORAGE_DRIVER;
// the DB only ever stores the key, so switching is an env change.
export type FileStorage = {
  put(key: string, data: Buffer, mime: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  remove(key: string): Promise<void>;
};

function localStorage(root: string): FileStorage {
  const base = path.resolve(root);
  // Keys are generated by the server, but never let one escape the upload folder.
  const resolve = (key: string) => {
    const full = path.resolve(base, key);
    if (!full.startsWith(base + path.sep)) throw new Error('Invalid storage key');
    return full;
  };
  return {
    async put(key, data) {
      const full = resolve(key);
      await mkdir(path.dirname(full), { recursive: true });
      await writeFile(full, data);
    },
    get: (key) => readFile(resolve(key)),
    remove: (key) => rm(resolve(key), { force: true }),
  };
}

function supabaseStorage(url: string, serviceKey: string, bucket: string): FileStorage {
  const endpoint = (key: string) => `${url.replace(/\/$/, '')}/storage/v1/object/${bucket}/${key.split('/').map(encodeURIComponent).join('/')}`;
  const auth = { Authorization: `Bearer ${serviceKey}`, apikey: serviceKey };
  const check = async (res: Response, what: string) => {
    if (!res.ok) throw new Error(`Supabase storage ${what} failed: ${res.status} ${await res.text()}`);
    return res;
  };
  return {
    async put(key, data, mime) {
      await check(await fetch(endpoint(key), { method: 'POST', headers: { ...auth, 'content-type': mime }, body: new Uint8Array(data) }), 'upload');
    },
    async get(key) {
      return Buffer.from(await (await check(await fetch(endpoint(key), { headers: auth }), 'download')).arrayBuffer());
    },
    async remove(key) {
      await check(await fetch(endpoint(key), { method: 'DELETE', headers: auth }), 'delete');
    },
  };
}

// Read from the environment on each call so tests can point it at a temp folder.
export function getStorage(): FileStorage {
  if (process.env.STORAGE_DRIVER === 'supabase') {
    const { SUPABASE_URL, SUPABASE_SERVICE_KEY, SUPABASE_BUCKET } = process.env;
    if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) throw new Error('STORAGE_DRIVER=supabase needs SUPABASE_URL and SUPABASE_SERVICE_KEY');
    return supabaseStorage(SUPABASE_URL, SUPABASE_SERVICE_KEY, SUPABASE_BUCKET || 'bme-files');
  }
  return localStorage(process.env.STORAGE_PATH || './uploads');
}
